export const imageMap = {
  tandoori_chicken: require('./Tandoori_Chicken.png'),
  dal_makhni: require('./dal_makhni.png'),
  cabbage: require('./cabbage.png'),
  butter_chicken: require('./butter_chicken.png'),
  paneer_butter_masala: require('./paneer_butter_masala.png'),
  rogan_josh: require('./rogan_josh.png'),
  paneer_tikka: require('./paneer_tikka.png'),
  chicken_tikka: require('./chiken_tikka.png'),
  gobi_pakora: require('./gobi_pakora.png'),
  seekh_kebab: require('./sheekh_kebab.png'),  
  gulab_jamun: require('./gulab_jamun.png'),
  kulfi: require('./kulfi.png'),
  ras_malai: require('./ras_malai.png'),
  jalebi: require('./jalebi.png'),
  naan: require('./naan.png'),
  raita: require('./raita.png'),
  achaar: require('./achaar.png'),
  papad: require('./papad.png'),
  default: require('./placeholder.png'),
};
